version: "3"
services:
  prom:
    image: prom/prometheus:v2.12.0
    volumes:
     - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
     - 9090:9090
    depends_on:
     - exporter
  pushgateway:
    image: prom/pushgateway:v0.9.1
    ports:
     - 9091:9091
    depends_on:
     - prom
  exporter:
    image: prom/node-exporter:v0.18.1
    ports:
     - "9100:9100"
  grafana:
    image: grafana/grafana:6.3.3
    ports:
     - "3000:3000"
    depends_on:
      - prom
